[package]
name = "stacks-encoding-native-js"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]
resolver = "2"

[profile.release]
lto = true

[profile.release-dev]
inherits = "release"
debug = true

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Use stacks-blockchain develop branch (commit hash as of 2022-03-01)
# Updated to `feat/c32-optimizations` branch https://github.com/stacks-network/stacks-blockchain/pull/3075
stacks-common = { git = "https://github.com/stacks-network/stacks-blockchain", branch = "feat/c32-optimizations" }
clarity = { git = "https://github.com/stacks-network/stacks-blockchain", branch = "feat/c32-optimizations" }
blockstack-core = { git = "https://github.com/stacks-network/stacks-blockchain", branch = "feat/c32-optimizations" }

hex-simd = { version = "0.5.0" }
simd-abstraction = { version = "0.5.0", features = ["alloc", "std"] }
regex = "1.5"
serde_json = "1.0"
git-version = "0.3.5"
lazy_static = "1.4.0"
unicode-segmentation = "1.9.0"
rand = "0.8.5"
byteorder = "1.4.3"

[dependencies.pprof]
# git = "https://github.com/YangKeao/pprof-rs"
# branch = "nongu-unwind"
# features = ["nongnu-libunwind", "flamegraph"]
git = "https://github.com/mornyx/pprof-rs"
branch = "unwind"
features = ["flamegraph"]
optional = true

[target.'cfg(all(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64"), not(target_env = "msvc")))'.dependencies]
sha2 = { version = "0.10", features = ["asm"] }

[target.'cfg(any(not(any(target_arch = "x86_64", target_arch = "x86", target_arch = "aarch64")), target_env = "msvc"))'.dependencies]
sha2 = { version = "0.10" }

[dependencies.neon]
version = "0.10.0"
# git = "https://github.com/zone117x/neon"
# rev = "bdb936a7fba8fb932fc61cbe529e06f65f75f9d9"
default-features = false
features = ["napi-6"]

[dev-dependencies]
flate2 = "1.0.22"

[features]
profiling = ["pprof"]
