name: build

on:
  push:
  workflow_dispatch:

jobs:
  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build_linux-x64-musl:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: apk add alpine-sdk git nodejs npm
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build-cargo
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64-musl
          path: native/linux-x64-musl.node
          if-no-files-found: error

  build_linux-x64-glibc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build-cargo
      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64-glibc
          path: native/linux-x64-glibc.node
          if-no-files-found: error

  build_linux-arm64-glibc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-gnu
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install cross compile deps
        run: |
          sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu libc6-dev-arm64-cross
      - name: Configure linux-arm64 cross compile
        run: |
          echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CC_aarch64_unknown_linux_gnu=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
          echo "CXX_aarch64_unknown_linux_gnu=aarch64-linux-gnu-g++" >> $GITHUB_ENV
          echo "TARGET_ARCH=arm64" >> $GITHUB_ENV
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build-cargo
      - uses: actions/upload-artifact@v2
        with:
          name: linux-arm64-glibc
          path: native/linux-arm64-glibc.node
          if-no-files-found: error

  build_win-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build-cargo
      - uses: actions/upload-artifact@v2
        with:
          name: win32-x64
          path: native/win32-x64.node
          if-no-files-found: error

  build_darwin-x64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build-cargo
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-x64
          path: native/darwin-x64.node
          if-no-files-found: error

  build_darwin-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Configure macos-arm64 cross compile
        run: |
          echo "SDKROOT=$(xcrun -sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)" >> $GITHUB_ENV
          echo "TARGET_ARCH=arm64" >> $GITHUB_ENV
      - name: npm i
        run: npm i
      - name: Build
        run: npm run build-cargo
      - uses: actions/upload-artifact@v2
        with:
          name: darwin-arm64
          path: native/darwin-arm64.node
          if-no-files-found: error